### ISSUE TITLE
Using Satlas Super Resolution for NDVI Purposes

### ISSUE THREAD

**Issue by lucalevi** [allenai/satlas-super-resolution#39]
Good day Piper! It's great to see such a good work being published and released to the public. We are a [company in Italy](https://www.geodatalab.it/) focusing on GIS and also satellite imagery and found your work. We would like to super-resolve Sentinel-2, most likely L2A data, in order to upscale 10 m-resolution images in the bands B04 and B08 to a resolution of 5 m and 2.5 m. 

# 1. Usage of L2A, B04 and B08 bands
I see [here](https://github.com/allenai/satlas-super-resolution/tree/main?tab=readme-ov-file#sentinel-2) that you use Sentinel-2 L1C imagery instead of L2A imagery, which is better suited to calculate indices like the NDVI since L2A imagery provides reflectance values closer to the Earth's surface. 

We are wondering whether you trained the model to account also for L2A imagery and whether the model weights you provide can also be used to super-resolve imagery in the bands B04 and B08 or whether you just focus on the TCI.jp2 files in the RGB channels. It would be also useful to know whether you have case studies in agriculture and/or you experimented with a super-resolved NDVI.

# 2. Resolution of the super-resolved images
Further, one thing is not clear to me: if I run inference on an image at 10 m resolution, which resolution am I going to get in the super-resolved image? [EDIT: "_All models are trained to upsample by a factor of 4_" from [here](https://github.com/allenai/satlas-super-resolution/tree/main?tab=readme-ov-file#model), thus 10 m original -> 2.5 m super-resolved]

# 3. Adaptation of the .yml files to bands other than RGB
One more thing: I don't fully understand the infer_example.yml file: to run inference on a single image using the provided weights I have to adapt the sections of the infer_example.yml file with the informations of the .yml files mentioned next to the weight [here](https://github.com/allenai/satlas-super-resolution/?tab=readme-ov-file#model-weights). In such an instance, I have the following configuration file called "infer_ESRGAN_1S2.yml" taking the configuration, namely the **network structure**, written in the [esrgan_baseline_1S2.yml](https://github.com/allenai/satlas-super-resolution/blob/experiments/ssr/options/experiments/esrgan_baseline_1S2.yml) file.

**infer_ESRGAN_1S2.yml** follows
```
# General Settings
name: infer_ESRGAN_1S2
model_type: SSRESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

# Inference Settings

# Root directory for low-res images you want super-resolved.
# This can be in any directory structures, but the code expects pngs.
data_dir: ssr/low_res_imgs/

n_lr_images: 1 %  change to match the esrgan model (the weight)

save_path: ssr/resolved_imgs/

# Structure of the generator you want to use for inference
network_g:
  type: SSR_RRDBNet
  num_in_ch: 3  % number of Sentinel2 images * 3 channels (RGB)
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# Load pretrained weights into the generator that is defined above
path:
  pretrain_network_g: ssr/weights/esrgan_1S2.pth
  param_key_g: params_ema
  strict_load_g: true
```

Apparently, this is what is needed to run inference on a single image, but what if I want to do it on just a single channel, like for the bands B04 and B08 that are greyscale, and not the 3 RGB channels typical of the TCI.jp2 images? The line `num_in_ch: 3  # number of Sentinel2 images * 3 channels (RGB)` suggests that I have to use RGB images. Thus, I am wondering whether these yml files and more generally the inference using the pre-trained weights can be accomplished on single bands with single channels, namely the greyscale bands B04 and B08.

# 4. Shapes of the images, conversion from .jp2 to PNG
I also have another issue about the "shape" of the images, but I think that [here](https://github.com/allenai/satlas-super-resolution/?tab=readme-ov-file#how-to-process-raw-sentinel-2-data) I will format them in the appropriate way. I still have to experiment with it, but I don't know whether I will get PNG images. It would be useful to potentially upscale jp2, original Sentinel-2 images, without the need of reshaping or converting them. But I think this is an architectural feature of the model not easily modifiable (will be grateful though to hear your opinion on it.) 

I have issues with the shapes of the images. It should be [32, 32, 3] but a, say, Sentinel-2 10 m, TCI image, even being a PNG, has shape [10980 , 10980, 3]. In my experiment I tried to convert the .jp2 images to PNG using `gdal_translate -of PNG your_sentinel_scene.jp2 your_sentinel_scene.png
`, but I am wondering whether it is the right way to go. Will try with the code you provide, even if I don't see any PNG image being outputted from the code [here](https://github.com/allenai/satlas-super-resolution/?tab=readme-ov-file#how-to-process-raw-sentinel-2-data). Further, where does the function _reproject_image_ come from? I don't see it being defined.

```
with rasterio.open(tci_jp2_path) as src:
    img_rep, meta_rep = reproject_image(
        img, meta, rasterio.crs.CRS.from_epsg(3857), [...])
```

[EDIT: the function reproject_image is indeed not defined, and the provided image conversion cannot be accomplished. We seek guidance as about the right image conversion to feed the model.]
        
Thanks for your support, will be interested to hear from you with new perspectives :) Cheers from Italy!
